In [2]:
import re
import numpy as np

In [3]:
with open('input8.txt', "r") as file:
    text = file.read().strip().split('\n')

In [46]:
blank = np.zeros([6, 50])
for i in text:
    a, b = re.findall('\d+', i)
    stuff = i.split(' ')
    a = int(a)
    b = int(b)
    if stuff[0].strip() == 'rect':
        blank[:b, :a] = 1
    elif stuff[0].strip() == 'rotate':
        if stuff[1].strip() == 'row':
            blank[a, :] = np.roll(blank[a, :], b)
        elif stuff[1].strip() == 'column':
            blank[:, a] = np.roll(blank[:, a], b)
        else:
            print('rect error')
    else:
        print('read error')

In [57]:
# Part 1
blank.sum()

115.0

In [56]:
# Part 2 - could add grid to letter ML
for i in range(0, blank.shape[1], 5):
    print(blank[:6, i: i + 5])
    print(' ') # EFEYKFRFIJ

[[1. 1. 1. 1. 0.]
 [1. 0. 0. 0. 0.]
 [1. 1. 1. 0. 0.]
 [1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [1. 1. 1. 1. 0.]]
 
[[1. 1. 1. 1. 0.]
 [1. 0. 0. 0. 0.]
 [1. 1. 1. 0. 0.]
 [1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]]
 
[[1. 1. 1. 1. 0.]
 [1. 0. 0. 0. 0.]
 [1. 1. 1. 0. 0.]
 [1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [1. 1. 1. 1. 0.]]
 
[[1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [0. 1. 0. 1. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0.]]
 
[[1. 0. 0. 1. 0.]
 [1. 0. 1. 0. 0.]
 [1. 1. 0. 0. 0.]
 [1. 0. 1. 0. 0.]
 [1. 0. 1. 0. 0.]
 [1. 0. 0. 1. 0.]]
 
[[1. 1. 1. 1. 0.]
 [1. 0. 0. 0. 0.]
 [1. 1. 1. 0. 0.]
 [1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]]
 
[[1. 1. 1. 0. 0.]
 [1. 0. 0. 1. 0.]
 [1. 0. 0. 1. 0.]
 [1. 1. 1. 0. 0.]
 [1. 0. 1. 0. 0.]
 [1. 0. 0. 1. 0.]]
 
[[1. 1. 1. 1. 0.]
 [1. 0. 0. 0. 0.]
 [1. 1. 1. 0. 0.]
 [1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]]
 
[[0. 1. 1. 1. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 1. 1. 1. 0.]]
 
[